vespawatch/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'vespawatch'


urlpatterns = [
    path('', views.index, name='index'),
    path('get-involved/', views.getinvolved, name='getinvolved'),
    path('identification/', views.identification, name='identification'),

    path('about/links/', views.about_links, name='about_links'),
    path('about/management/', views.about_management, name='about_management'),
    path('about/privacy-policy/', views.about_privacypolicy, name='about_privacypolicy'),
    path('about/project/', views.about_project, name='about_project'),
    path('about/vespa-velutina/', views.about_vespavelutina, name='about_vespavelutina'),

    path('management/', views.management, name='management'),
    path('management/nest/<int:pk>/', views.nest_detail, name='nest-detail'),

    path('obs/', views.latest_observations, name='latest-observations'),
    path('obs/add/', views.obs_create, name='observation-add'),

    path('obs/individual/', RedirectView.as_view(pattern_name='vespawatch:individual-add')),
    path('obs/individual/add/', views.create_individual, name='individual-add'),

    path('obs/nest/', RedirectView.as_view(pattern_name='vespawatch:nest-add')),
    path('obs/nest/add/', views.create_nest, name='nest-add'),

    path('profile', views.profile, name='profile'),

    # API paths
    #path('api/observations/', views.observations_json, name='api_observations'),  TODO can we remove this one?
    path('api/individuals/', views.individuals_json, name='api_individuals'),
    path('api/individuals/<int:pk>', views.single_individual_json, name='api_single_individual'), # TODO can we remove this one?
    path('api/individual_pictures/', views.save_individual_picture, name='api_individual_picture'),
    path('api/individual_pictures/<int:pk>', views.get_individual_picture, name='api_single_individual_picture'),
    path('api/nests/', views.nests_json, name='api_nests'),
    path('api/nests/<int:pk>/', views.single_nest_json, name='api_single_nest'), # TODO can we remove this one?
    path('api/nest_pictures/', views.save_nest_picture, name='api_nest_picture'),
    path('api/nest_pictures/<int:pk>', views.get_nest_picture, name='api_single_nest_picture'),

    path('api/action_outcomes/', views.management_actions_outcomes_json, name='api_action_outcomes'),
    path('api/save_management_action/', views.save_management_action, name='api_action_save'),
    path('api/get_management_action/', views.get_management_action, name='api_action_get'),
    path('api/delete_management_action/', views.delete_management_action, name='api_action_delete'),
]

vespawatch/forms.py
from django.forms import inlineformset_factory, ModelForm, BooleanField, ChoiceField, IntegerField, EmailField, CharField
from django.utils.translation import ugettext_lazy as _
from vespawatch.fields import ISODateTimeField
from .models import ManagementAction, Nest, Individual, NestPicture, IndividualPicture, Profile


OBS_FORM_VUE_FIELDS = ({'field_name': 'observation_time', 'attribute_if_error': 'date_is_invalid'},
                       {'field_name': 'latitude', 'attribute_if_error': 'latitude_is_invalid'},
                       {'field_name': 'longitude', 'attribute_if_error': 'longitude_is_invalid'},
                       )


class ReportObservationForm(ModelForm):
    privacy_policy = BooleanField(label=_('I agree with the <a href="/about/privacy-policy/" target="_blank">privacy policy</a>'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for vue_field in OBS_FORM_VUE_FIELDS:
            setattr(self, vue_field['attribute_if_error'], False)

    def clean(self):
        cleaned_data = self.cleaned_data
        self.errors_as_json = self.errors.as_json()

        for vue_field in OBS_FORM_VUE_FIELDS:
            if vue_field['field_name'] in self.errors:
                setattr(self, vue_field['attribute_if_error'], True)

        return cleaned_data


class IndividualForm(ReportObservationForm):
    redirect_to = ChoiceField(choices=(('index', 'index'), ('management', 'management')), initial='index')
    card_id = IntegerField()
    location = CharField(max_length=255, required=False)
    image_ids = CharField(max_length=255)
    observer_email = EmailField(label=_('Email address'))

    class Meta:
        model = Individual
        fields = ['taxon', 'individual_count', 'behaviour', 'latitude', 'longitude',
                  'observation_time', 'comments',
                  'observer_name', 'observer_email', 'observer_phone'
        ]
        field_classes = {
            'observation_time': ISODateTimeField,
        }

    def clean(self):
        cleaned_data = super().clean()
        if 'image_ids' not in cleaned_data or not cleaned_data['image_ids']:
            msg = 'You must add at least one picture'
            self.add_error(None, msg)
            setattr(self, "image_is_invalid", True)

        return cleaned_data

    def save(self, *args, **kwargs):
        observation = super().save(*args, **kwargs)
        image_ids = [x for x in self.cleaned_data['image_ids'].strip().split(',') if x]
        for image_id in image_ids:
            np = IndividualPicture.objects.get(pk=image_id)
            np.observation = observation
            np.save()


class NestForm(ReportObservationForm):
    redirect_to = ChoiceField(choices=(('index', 'index'), ('management', 'management')), initial='index')
    card_id = IntegerField()
    height = ChoiceField(label=_('Nest height'), choices=[('', '--------')] + list(Nest.HEIGHT_CHOICES))
    location = CharField(max_length=255, required=False)
    image_ids = CharField(max_length=255)
    observer_name = CharField(label=_('Name'), max_length=255)
    observer_email = EmailField(label=_('Email address'))
    observer_phone = CharField(label=_('Telephone number'), max_length=20)

    class Meta:
        model = Nest
        fields = ['taxon', 'latitude', 'longitude', 'municipality',
                  'observation_time', 'size', 'height', 'comments',
                  'observer_name', 'observer_email', 'observer_phone',
                  'expert_vv_confirmed'
        ]
        field_classes = {
            'observation_time': ISODateTimeField,
        }

    def clean(self):
        cleaned_data = super().clean()

        if 'image_ids' not in cleaned_data or not cleaned_data['image_ids']:
            msg = 'You must add at least one picture'
            self.add_error(None, msg)
            setattr(self, "image_is_invalid", True)
        return cleaned_data

    def save(self, *args, **kwargs):
        observation = super().save(*args, **kwargs)
        image_ids = [x for x in self.cleaned_data['image_ids'].strip().split(',') if x]
        for image_id in image_ids:
            np = NestPicture.objects.get(pk=image_id)
            np.observation = observation
            np.save()


class IndividualPictureForm(ModelForm):
    class Meta:
        model = IndividualPicture
        fields = ['observation', 'image']


class NestPictureForm(ModelForm):
    class Meta:
        model = NestPicture
        fields = ['observation', 'image']


IndividualImageFormset = inlineformset_factory(Individual, IndividualPicture, fields=('image',), extra=2)
NestImageFormset = inlineformset_factory(Nest, NestPicture, fields=('image',), extra=2)


class ManagementActionForm(ModelForm):
    class Meta:
        model = ManagementAction
        fields = ['user', 'nest', 'outcome', 'action_time', 'duration', 'person_name', 'comments', 'number_of_persons']

        field_classes = {
            'action_time': ISODateTimeField,
        }


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['organization', 'description', 'phone', 'email_notification']

vespawatch/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext as _
from django.http import JsonResponse, HttpResponseRedirect, HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import View
from django.views.generic.detail import BaseDetailView, SingleObjectMixin, SingleObjectTemplateResponseMixin
from django.views.generic.edit import DeletionMixin
from django.urls import reverse_lazy


from vespawatch.utils import ajax_login_required
from .forms import ManagementActionForm, IndividualForm, IndividualPictureForm, \
    NestForm, NestPictureForm, ProfileForm
from .models import Individual, Nest, ManagementAction, IdentificationCard, \
    get_observations, get_individuals, get_nests, IndividualPicture, NestPicture, Profile


class CustomBaseDetailView(SingleObjectMixin, View):
    """Subclassing this one to pass the request parameters to the kwargs of get_context_data"""
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object, **request.GET)
        return self.render_to_response(context)


class CustomBaseDeleteView(DeletionMixin, BaseDetailView):
    """Overriding the BaseDeleteView to add the redirect_to param from the request to the View object"""
    def delete(self, request, *args, **kwargs):
        r = request.GET.get('redirect_to', '')
        if r:
            self.requested_success_url = r
        return super(CustomBaseDeleteView, self).delete(request, *args, **kwargs)


class CustomDeleteView(SingleObjectTemplateResponseMixin, CustomBaseDeleteView):
    """Also had to override this one for adding the redirect_to param to the View object"""
    template_name_suffix = '_confirm_delete'


def index(request):
    return render(request, 'vespawatch/index.html', {'observations': get_observations(limit=4)})


def getinvolved(request):
    return render(request, 'vespawatch/simple_page_fragment.html', {'fragment_id': 'getinvolved'})


def identification(request):
    return render(request, 'vespawatch/simple_page_fragment.html', {'fragment_id': 'identification'})


def about_links(request):
    return render(request, 'vespawatch/simple_page_fragment.html', {'fragment_id': 'about_links'})


def about_management(request):
    return render(request, 'vespawatch/simple_page_fragment.html', {'fragment_id': 'about_management'})


def about_privacypolicy(request):
    return render(request, 'vespawatch/simple_page_fragment.html', {'fragment_id': 'about_privacypolicy'})


def about_project(request):
    return render(request, 'vespawatch/simple_page_fragment.html', {'fragment_id': 'about_project'})


def about_vespavelutina(request):
    return render(request, 'vespawatch/simple_page_fragment.html', {'fragment_id': 'about_vespavelutina'})


def latest_observations(request):
    return render(request, 'vespawatch/obs.html', {'observations': get_observations(limit=40)})


# CREATE UPDATE INDIVIDUAL OBSERVATIONS

def create_individual(request):
    if request.method == 'POST':
        redirect_to = request.POST.get('redirect_to')
        card_id = request.POST.get('card_id')
        identif_card = IdentificationCard.objects.get(pk=card_id)
        form = IndividualForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, _("Your observation was successfully created. Thanks for your contribution!"))
            return HttpResponseRedirect(reverse_lazy(f'vespawatch:{redirect_to}'))
    else:
        redirect_to = request.GET.get('redirect_to', 'index')
        identif_card_id = request.GET.get('card_id')
        identif_card = IdentificationCard.objects.get(pk=identif_card_id)
        image_ids = request.GET.get('image_ids', '')
        taxon = identif_card.represented_taxon
        form = IndividualForm(initial={
            'redirect_to': redirect_to,
            'card_id': identif_card_id,
            'image_ids': image_ids,
            'taxon': taxon})
    return render(request, 'vespawatch/individual_create.html',
                  {'form': form, 'type': 'individual', 'identif_card': identif_card})


# CREATE UPDATE NEST OBSERVATIONS

def create_nest(request):
    if request.method == 'POST':
        redirect_to = request.POST.get('redirect_to')
        card_id = request.POST.get('card_id')
        identif_card = IdentificationCard.objects.get(pk=card_id)
        form = NestForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, _("Your observation was successfully created. Thanks for your contribution!"))
            return HttpResponseRedirect(reverse_lazy(f'vespawatch:{redirect_to}'))
    else:
        redirect_to = request.GET.get('redirect_to', 'index')
        identif_card_id = request.GET.get('card_id')
        image_ids = request.GET.get('image_ids', '')
        identif_card = IdentificationCard.objects.get(pk=identif_card_id)
        taxon = identif_card.represented_taxon
        form = NestForm(initial={
            'redirect_to': redirect_to,
            'card_id': identif_card_id,
            'image_ids': image_ids,
            'taxon': taxon
        })
    return render(request, 'vespawatch/nest_create.html',
                  {'form': form, 'type': 'nest', 'identif_card': identif_card})


@login_required
def profile(request):
    if hasattr(request.user, 'profile'):
        profile = request.user.profile
    else:
        profile = Profile(user=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, _('Your profile was successfully updated.'))
            return HttpResponseRedirect(reverse_lazy(f'vespawatch:index'))
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'vespawatch/profile.html', {'form': form, 'username': request.user.username})


@login_required
def management(request):
    return render(request, 'vespawatch/management.html')


@login_required
def nest_detail(request, pk=None):
    nest = get_object_or_404(Nest, pk=pk)
    action = nest.managementaction if nest.controlled else None
    return render(request, 'vespawatch/nest_detail.html', {'nest': nest, 'action': action,
                                                           'editable': nest.editable_by_user(request.user)})


def obs_create(request):
    # This is the step where the user select the species and type (nest/individual)
    cards = IdentificationCard.objects.all()

    return render(request, 'vespawatch/obs_create.html', {'identification_cards': cards})

# ==============
# API methods
# ==============

def observations_json(request):
    """
    Return all observations as JSON data.
    """
    # TODO: can we deprecate this function? + If so, can we remove the prefetch_related('pictures') from the get_observations function?

    obs_type = request.GET.get('type', None)
    include_individuals = (obs_type == 'individual' or obs_type is None)
    include_nests = (obs_type == 'nest' or obs_type is None)

    limit = request.GET.get('limit', None)
    limit = int(limit) if limit is not None else None

    obs = get_observations(include_individuals=include_individuals,
                           include_nests=include_nests,
                           limit=limit)

    light = request.GET.get('light', None)

    if light:
        response = JsonResponse({
            'observations': [model_to_dict(x) for x in obs]
        })
    else:
        response = JsonResponse({
            'observations': [x.as_dict() for x in obs]
        })

    return response


def individuals_json(request):
    """
    Return all individuals as JSON data.
    """
    limit = request.GET.get('limit', None)
    limit = int(limit) if limit is not None else None

    light = request.GET.get('light', None)
    vv_only = request.GET.get('vvOnly', None)
    flanders_only = request.GET.get('flOnly', 'false') == 'true'

    obs = get_individuals(limit=limit, vv_only=vv_only, flanders_only=flanders_only)

    if light:
        response = JsonResponse({
            'individuals': [model_to_dict(x) for x in obs]
        })
    else:
        response = JsonResponse({
            'individuals': [x.as_dict() for x in obs]
        })

    return response


def single_individual_json(request, pk=None):
    """
    Get a single individual and return it as JSON
    """
    return JsonResponse(get_object_or_404(Individual, pk=pk).as_dict())


def single_nest_json(request, pk=None):
    """
    Get a single nest and return it as JSON
    """
    return JsonResponse(get_object_or_404(Nest, pk=pk).as_dict())


def nests_json(request):
    """
    Return all nests as JSON data.
    """
    limit = request.GET.get('limit', None)
    limit = int(limit) if limit is not None else None

    light = request.GET.get('light', None)
    vv_only = request.GET.get('vvOnly', False) == 'true'
    confirmed_only = request.GET.get('confirmedOnly', False) == 'true'
    include_pictures = request.GET.get('includePictures', 'true') == 'true'
    flanders_only = request.GET.get('flOnly', 'false') == 'true'

    obs = get_nests(limit=limit, vv_only=vv_only, confirmed_only=confirmed_only, flanders_only=flanders_only)

    if light:
        response = JsonResponse({
            'nests': [model_to_dict(x) for x in obs]
        })
    else:
        response = JsonResponse({
            'nests': [x.as_dict(request_user=request.user, include_pictures=include_pictures) for x in obs]
        })

    return response


def management_actions_outcomes_json(request):
    #TODO: Implements sorting?
    #TODO: Implements i18n?
    outcomes = ManagementAction.OUTCOME_CHOICE

vespawatch/templates/vespawatch/base.html
{% load static %}
{% load i18n %}
{% load custom_tags %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{{ settings.WEBSITE_NAME }}</title>

    <script type="text/javascript">
      var VWConfig = {% js_config_object %};
    </script>

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'vespawatch/icons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'vespawatch/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'vespawatch/icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'vespawatch/icons/site.webmanifest' %}" crossorigin="use-credentials">
    <link rel="mask-icon" href="{% static 'vespawatch/icons/safari-pinned-tab.svg' %}" color="#ea792a">
    <link rel="shortcut icon" href="{% static 'vespawatch/icons/favicon.ico' %}">
    <meta name="msapplication-TileColor" content="#ea792a">
    <meta name="msapplication-config" content="{% static 'vespawatch/icons/browserconfig.xml' %}">
    <meta name="theme-color" content="#ffffff">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'vespawatch/libraries/leaflet/leaflet.css' %}">
    <link rel="stylesheet" href="{% static 'vespawatch/libraries/vue/vue-datetime.min.css' %}">
    <link rel="stylesheet" href="{% static 'vespawatch/libraries/vue/vue2Dropzone.min.css' %}">
    <link rel="stylesheet" href="{% static 'vespawatch/css/main.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'vespawatch:index' %}">
          <img src="{% static 'vespawatch/img/avatar.jpg' %}" class="d-inline-block align-top" alt="">
          {{ settings.WEBSITE_NAME }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        {% url 'vespawatch:management' as management_url %}
        {% url 'vespawatch:getinvolved' as getinvolved_url %}
        {% url 'vespawatch:identification' as identification_url %}
        {% url 'vespawatch:about_vespavelutina' as about_vespavelutina_url %}
        {% url 'vespawatch:about_management' as about_management_url %}
        {% url 'vespawatch:about_project' as about_project_url %}
        {% url 'vespawatch:about_privacypolicy' as about_privacypolicy_url %}
        {% url 'vespawatch:about_links' as about_links_url %}
        
        <div class="collapse navbar-collapse" id="navbar-content">
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link{% if request.path == management_url %} active{% endif %}" href="{{ management_url }}">{% trans 'Management' %}</a>
              </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link{% if request.path == getinvolved_url %} active{% endif %}" href="{{ getinvolved_url }}">{% trans 'Get involved' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link{% if request.path == identification_url %} active{% endif %}" href="{{ identification_url }}">{% trans 'Identification' %}</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="about-dropdown" role="button" data-toggle="dropdown">{% trans 'About' %}</a>
              <div class="dropdown-menu">
                <a class="dropdown-item{% if request.path == about_vespavelutina_url %} active{% endif %}" href="{{ about_vespavelutina_url }}">{% trans 'Vespa velutina' %}</a>
                <a class="dropdown-item{% if request.path == about_management_url %} active{% endif %}" href="{{ about_management_url }}">{% trans 'Management' %}</a>
                <a class="dropdown-item{% if request.path == about_project_url %} active{% endif %}" href="{{ about_project_url }}">{% trans 'Project' %}</a>
                <a class="dropdown-item{% if request.path == about_privacypolicy_url %} active{% endif %}" href="{{ about_privacypolicy_url }}">{% trans 'Privacy policy' %}</a>
                <a class="dropdown-item{% if request.path == about_links_url %} active{% endif %}" href="{{ about_links_url }}">{% trans 'Links' %}</a>
              </div>
            </li>
          </ul>
          
          <ul class="navbar-nav mr-3">
            {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="user-dropdown" role="button" data-toggle="dropdown">{{ user.username }}</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'vespawatch:profile' %}">{% trans 'My profile' %}</a>
                  <a class="dropdown-item" href="{% url 'logout' %}">{% trans 'Log out' %}</a>
                </div>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="btn btn-primary btn-sm" href="{% url 'login' %}">{% trans 'Log in' %}</a>
              </li>
            {% endif %}
          </ul>

          <ul class="navbar-nav">
            <form class="form-inline" action="{% url 'set_language' %}" method="post" id="lang-form">
              {% csrf_token %}
              <input name="next" type="hidden" value="{{ redirect_to }}">
              <select class="form-control form-control-sm" name="language" id="lang">
                {% get_current_language as LANGUAGE_CODE %}
                
                {% if user.is_superuser %}
                  {# Superusers get access to languages that are not yet officially available }
                  {% get_language_info_list for settings.LANGUAGES as languages %}
                {% else %}  
                  {% get_language_info_list for settings.LANGUAGES_AVAILABLE_IN_SELECTOR as languages %}
                {% endif %}
                
                {% for language in languages %}
                  <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>{{ language.name_local }}</option>
                {% endfor %}
              </select>
            </form>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-9">
            <p>
              <a class="mr-3" href="https://www.inbo.be"><img src="{% static 'vespawatch/img/logo_inbo.png' %}" height="40" alt=""></a>
              <a href="https://www.honeybeevalley.eu/"><img src="{% static 'vespawatch/img/logo_honeybeevalley.png' %}" height="40" alt=""></a>
            </p>
            <p>
              {% blocktrans %}
                This project was funded by <a href="https://www.ewi-vlaanderen.be/oproep-citizen-science-geselecteerde-projecten">EWI</a>
                and developed by the <a href="https://oscibio.inbo.be">Open science lab for biodiversity</a>.
                Thanks to the <a href="https://www.inaturalist.org/">iNaturalist community</a> for verifying observations.
                INBO is a member of the <a href="http://ecsa.citizen-science.net/">European Citizen Science Association (ECSA)</a>.
              {% endblocktrans %}
            </p>
          </div>
          <div class="col-lg-3">
            <ul class="list-unstyled">
              <li><a href="{% url 'vespawatch:about_project' %}">{% trans 'About this project' %}</a></li>
              <li><a href="{% url 'vespawatch:about_privacypolicy' %}">{% trans 'Privacy policy' %}</a></li>
              <li><a href="mailto:vespawatch@inbo.be">{% trans 'Contact us' %}</a></li>
              <li><a href="https://github.com/inbo/vespa-watch">{% trans 'Source code' %}</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    <!-- JS -->
    <script src="{% static 'vespawatch/libraries/bootstrap/jquery.min.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/bootstrap/bootstrap.min.js' %}"></script>
    
    {% if settings.JS_DEBUG %}
      {# see https://vuejs.org/v2/guide/deployment.html#Without-Build-Tools #}
      <script src="{% static 'vespawatch/libraries/vue/vue.js' %}"></script>
    {% else %}
      <script src="{% static 'vespawatch/libraries/vue/vue.min.js' %}"></script>
    {% endif %}
    
    <script src="{% static 'vespawatch/libraries/vue/luxon.min.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/vue/vue-datetime.min.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/vue/vuejs-paginate.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/vue/vue2Dropzone.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/axios/axios.min.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/crossfilter/crossfilter.min.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/leaflet/leaflet.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/leaflet/leaflet-geosearch.min.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/leaflet/spin.min.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/leaflet/leaflet.spin.min.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/moment/moment.min.js' %}"></script>
    <script src="{% static 'vespawatch/libraries/wnumb/wnumb.js' %}"></script>
    <script src="{% url 'javascript-catalog' %}"></script>
    <script src="{% static 'vespawatch/js/app.min.js' %}"></script>
  </body>
</html>

vespawatch/templates/vespawatch/index.html
{% extends 'vespawatch/base.html' %}
{% load static %}
{% load i18n %}
{% load page_fragments %}

{% block content %}
<figure>
  <div class="jumbotron jumbotron-fluid" style="background-image: linear-gradient(to right, rgba(62, 96, 16, 0.75), rgba(0, 0, 0, 0)), url('{% static 'vespawatch/img/cover.jpg' %}')">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1>{% trans 'Monitor the invasion of the Asian hornet' %}</h1>
          <a class="btn btn-lg btn-primary" href="{% url 'vespawatch:observation-add' %}">{% trans 'Report a hornet' %}</a>
        </div>
      </div>
    </div>
  </div>
  <figcaption>
    {% trans 'Photo by' %} <a href="https://www.inaturalist.org/observations/17322380">Karel Schoonvaere</a>
  </figcaption>
</figure>

<main class="container" id="vw-main-app">
  {% if messages %}
    <div class="messages">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
      {% endfor %}
    </div>
  {% endif %}

  <div class="row">
    <div class="col-md-4">
      {% get_page_fragment 'welcome' %}
    </div>

    <div class="col-md-8">
      <vw-observations-viz load-data="1"></vw-observations-viz>
    </div>
  </div>

  <h2>{% trans 'Latest observations' %}</h2>

  {% include 'vespawatch/includes/obs_cards.html' %}

  <p class="text-right"><a href="{% url 'vespawatch:latest-observations' %}">
    {% trans 'See more observations' %} »</a>
  </p>
</main>
{% endblock %}